spring:
  application:
    name: hello-service
  config:
    import: optional:configserver:http://config-server:8888
  profiles:
    active: local

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

server:
  port: 4567