spring:
  application:
    name: hello-service
  config:
    import: optional:configserver:http://config-server:${CONFIG_PORT:8888}
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:local}


eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA-SERVER:localhost}:${EUREKA_PORT:8761}/eureka/

server:
  port: ${HELLO_SERVICE_PORT:4567}

  